version: "3.8"

# =====================
# Services
# =====================
services:
  # NGINX Reverse Proxy Container
  reverse-proxy:
    image: nginx:1.23.2
    container_name: reverse-proxy
    depends_on:
      - database
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    networks:
      - auth-net

  # Database Container
  database:
    image: mysql:8
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3306
    networks:
      - auth-net

  # Front-end React Container
  frontend:
    container_name: frontend
    build:
      context: ./client
    ports: 
      - 3000:3000
    restart: on-failure
    networks:
      - auth-net

  # Back-end Spring Boot Container
  backend:
    container_name: backend
    ports:
      - 8080:8080
    build:
      context: ./server
    depends_on:
      - database
    restart: on-failure
    networks:
      - auth-net

# ======================
# Docker Virtual Network
# ======================
networks:
  auth-net:
    name: auth-net
    external: false

