server:
  port: 8080

rsa:
  private-key: certs/private.pem
  public-key: certs/public.pem

spring:
  config:
    import: optional:secrets.yml
  datasource:
#   url: SECRET
#   username: SECRET
#   password: SECRET
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    protocol: smtp
#   username: SECRET
#   password: SECRET
    properties.mail.smtp:
          starttls.enable: true
          timeout: 3000
          connection-timeout: 5000
          write-timeout: 5000
          auth: true
          ssl.trust: smtp.gmail.com



