server:
  port: 8080

rsa:
  private-key: certs/private.pem
  public-key: certs/public.pem

spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: jdbc:mysql://database:3306/authdb
  #   username: SECRET
  #   password: SECRET
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    #   username: SECRET
    #   password: SECRET
    properties.mail.smtp:
      starttls.enable: true
      timeout: 3000
      connection-timeout: 5000
      write-timeout: 5000
      auth: true
      ssl.trust: smtp.gmail.com
